apiVersion: v2
name: devx-helloworld-springboot-test-qby70
description: Chart for creating devx-helloworld-springboot-test-qby70 and ingress mapping our Flexport EKS clusters

type: application
version: 0.1.0
